import { v4 as uuidv4 } from 'uuid';
export  default {
    works:[
        {
            id:uuidv4(),
            type:'fullstack',
            name:'Admin panel',
            image:'adminka.png',
            description:'This is a pet project admin panel with Laravel/Vue. Here you can add new users, update, and delete. Create appointments, update, delete, set settings from the admin panel, and edit profile info. Also here I did authentication with validation and redirect',
            link:'https://github.com/teddi90/profile_laravel_vue_api',
            year:'2024',
            project_link:'https://github.com/teddi90/profile_laravel_vue_api',
            technologies:['Laravel','Vue3','Tailwind'],
        },
        {
            id:uuidv4(),
            type:'fullstack',
            name:'Vshop',
            image:'vshop.png',
            description:'This is a pet project shop with Laravel/Inertia/Vue. Has full functionality of the shop as manipulation with cart and filtering products, also has an admin page where you can add new products, update, delete',
            link:'https://github.com/teddi90/Vshop',
            year:'2024',
            project_link:'https://github.com/teddi90/Vshop',
            technologies:['Laravel','Vue3','Inertia','Stripe','Tailwind'],
        },
        {
            id:uuidv4(),
            type:'frontend',
            name:'Ligvo Club',
            image:'ligvo_club.png',
            description:'Site for game board club where was used Nuxt/WordPress headless technology. The site has a parallax effect, game filter, validate form, slider',
            link:'https://ligvo-club.grt-team.com/',
            year:'2023',
            project_link:'https://github.com/teddi90/ligvo-club',
            technologies:['Nuxt3','WordPress','Pinia','Boostrap','Mapbox'],
        },
        {
            id:uuidv4(),
            type:'frontend',
            name:'Ligvo',
            image:'ligvo.png',
            description:'Site for game board club. Simple site with animation and map',
            link:'https://ligvo.grt-team.com/',
            year:'2023',
            project_link:'https://github.com/teddi90/ligvo',
            technologies:['Nuxt3','Boostrap','Mapbox'],
        },
        {
            id:uuidv4(),
            type:'pet_project',
            name:'Trello clone',
            image:'trello.png',
            description:'Task manager app where you can enter new tasks, delete them, move them to different columns, or change their order in the column. All states are recorded in local storage',
            link:'https://trello-clone-one-murex.vercel.app/',
            year:'2024',
            project_link:'https://github.com/teddi90/trello_clone',
            technologies:['Vue3','Pinia','Drag & Drop','Tailwind'],
        },
        {
            id:uuidv4(),
            type:'frontend',
            name:'Bird',
            image:'bird.jpg',
            description:'A site for a printing studio. A fully responsive site with sliders that was built for WordPress',
            link:'https://teddi90.github.io/bird/',
            year:'2022',
            project_link:'https://github.com/teddi90/bird',
            technologies:['HTML', 'CSS', 'SCSS'],
        },
        {
            id:uuidv4(),
            type:'frontend',
            name:'Fooseeshoes',
            image:'shoes.jpg',
            description:'Exam paper for an internship in the company. A fully responsive one-page store with a slider and banners that change content',
            link:'https://github.com/teddi90/fooseeshoes',
            year:'2019',
            project_link:'https://teddi90.github.io/fooseeshoes/',
            technologies:['HTML', 'CSS', 'SCSS','JavaScript','jQuery'],
        },
        {
            id:uuidv4(),
            type:'frontend',
            name:'Legal Services',
            image:'divorce.jpg',
            description:'Freelance project for lawyers. Simple landing page a fully adaptive webpage',
            link:'https://teddi90.github.io/divorce.github.io/',
            year:'2019',
            project_link:'https://github.com/teddi90/divorce.github.io',
            technologies:['HTML', 'CSS', 'SCSS', ],
        },
        {
            id:uuidv4(),
            type:'frontend',
            name:'M|Design',
            image:'mdesign.png',
            description:'Site for a design studio. I created the main page and separate pages with works from the portfolio',
            link:'https://teddi90.github.io/mdesign/',
            year:'2018',
            project_link:'https://github.com/teddi90/mdesign',
            technologies:['HTML', 'CSS', 'SCSS', 'Jquery'],
        },

    ]
}